# SPDX-FileCopyrightText: 2020 Diego Elio Petten√≤
#
# SPDX-License-Identifier: Unlicense

repos:
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://github.com/fsfe/reuse-tool
    rev: v0.12.1
    hooks:
    - id: reuse
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/pylint
    rev: v2.11.1
    hooks:
    -   id: pylint
        name: pylint (library and examples)
        types: [python]
        args:
            - "parallel64/"
            - --disable=duplicate-code
            - --ignore=conf.py
    -   id: pylint
        name: pylint (test code)
        description: Run pylint rules on "tests/*.py" files
        types: [python]
        files: "^tests/"
        args:
            - --disable=missing-docstring,duplicate-code
